In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
from os import path
import os
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import to_categorical
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_auc_score,accuracy_score
import warnings
warnings.filterwarnings('ignore')

Using TensorFlow backend.


In [5]:
for i in range(1,30):
    s = 'user_features/user'
    s+=str(i)+'_cb.txt'
    if(path.exists(s)):
        print(s)
        dataset =  np.loadtxt(s,delimiter = " ")
        if dataset.ndim == 1:
            dataset.shape = (1,10)
        y = dataset[:,9]
        X = dataset[:,0:9]
        y = to_categorical(y,num_classes=4)
        #print(X.shape,y.shape)
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2,random_state=0)
        X_train = sc.fit_transform(X_train)
        X_test = sc.transform(X_test)
        classifier = Sequential()
        classifier.add(Dense(output_dim = 8, activation = 'tanh', input_dim = 9))
        classifier.add(Dense(output_dim = 8, activation = 'relu'))
        classifier.add(Dense(output_dim = 8, activation = 'relu'))
        classifier.add(Dense(output_dim = 8, activation = 'relu'))
        classifier.add(Dense(output_dim = 8, activation = 'relu'))
        
        #classifier.add(Dense(output_dim = 128, init = 'uniform', activation = 'sigmoid'))
        #classifier.add(Dense(output_dim = 128, init = 'uniform', activation = 'relu'))
        #classifier.add(Dense(output_dim = 128, init = 'uniform', activation = 'sigmoid'))
        #classifier.add(Dense(output_dim = 128, init = 'uniform', activation = 'relu'))
        classifier.add(Dense(output_dim = 4, init = 'uniform', activation = 'softmax'))
        classifier.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])
        classifier.fit(X_train, y_train, batch_size = 4, nb_epoch = 100,verbose=0)
        y_pred = np.argmax(classifier.predict(X_train),axis=1)
        y_pred=to_categorical(y_pred,num_classes=4)
        #print(y_pred[0])
        ac=accuracy_score(y_train.argmax(axis=1), y_pred.argmax(axis=1))
        cm = confusion_matrix(y_train.argmax(axis=1), y_pred.argmax(axis=1))
        print(cm, ac,len(y_train))
        del classifier

user_features/user1_cb.txt
[[179   3  32]
 [  7  13  20]
 [ 67   2  74]] 0.6700251889168766 397
user_features/user2_cb.txt
[[105   5   7]
 [ 13 175   2]
 [ 37  13  14]] 0.7924528301886793 371
user_features/user5_cb.txt
[[104  10   0]
 [ 18  91  12]
 [ 11  26  35]] 0.749185667752443 307
user_features/user6_cb.txt
[[94  8 18]
 [17 12 20]
 [11  4 48]] 0.6637931034482759 232
user_features/user7_cb.txt
[[106   0  13]
 [  7   0  11]
 [  8   0  33]] 0.7808988764044944 178
user_features/user9_cb.txt
[[90 23  1]
 [19 75 27]
 [ 8 24 40]] 0.6677524429967426 307
user_features/user10_cb.txt
[[28  0 14]
 [10  0 10]
 [14  0 16]] 0.4782608695652174 92
user_features/user11_cb.txt
[[40  0  2]
 [ 1  9  1]
 [ 8  2 11]] 0.8108108108108109 74
user_features/user12_cb.txt
[[160   2   8]
 [ 15 173   4]
 [ 65  12  22]] 0.7700650759219089 461
user_features/user13_cb.txt
[[42  0  1]
 [ 2  7  2]
 [ 4  0 16]] 0.8783783783783784 74
user_features/user14_cb.txt
[[156   0  53]
 [  5  12  22]
 [ 28   3 118]] 0.720403022